services:
  web-public:
    build:
      context: .
      target: production
      args:
        VITE_ENABLE_PRIVATE: '0'
    env_file:
      - .env
    environment:
      ASSET_DIR: /usr/share/nginx/html
      APP: VITE_
    ports:
      - '8081:8080'
