services:
  web-private:
    build:
      context: .
      target: production
      args:
        VITE_ENABLE_PRIVATE: '1'
    env_file:
      - .env
    environment:
      ASSET_DIR: /usr/share/nginx/html
      APP: VITE_
    ports:
      - '8080:8080'
