"""v3

Revision ID: 1da98969b045
Revises: 
Create Date: 2025-04-07 12:08:35.194146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1da98969b045'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('user', 'security', 'admin', name='roleenum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_email')
    )
    op.create_table('verify_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('verification_code', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='emailrequeststatusenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('associated_user_id', sa.UUID(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['associated_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('forms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_to_visit_id', sa.UUID(), nullable=False),
    sa.Column('passport_full_name', sa.Text(), nullable=False),
    sa.Column('passport_series', sa.String(), nullable=False),
    sa.Column('passport_number', sa.String(), nullable=False),
    sa.Column('passport_who_issued', sa.Text(), nullable=False),
    sa.Column('passport_issue_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('passport_photo', sa.Text(), nullable=False),
    sa.Column('visit_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('visit_reason', sa.Text(), nullable=False),
    sa.Column('email_to_send_reply', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_to_visit_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visit_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('who_processed_user_id', sa.UUID(), nullable=True),
    sa.Column('who_processed_security_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('not_processed', 'reject', 'accept', name='visitrequeststatusenum'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.ForeignKeyConstraint(['who_processed_security_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['who_processed_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visit_requests')
    op.drop_table('forms')
    op.drop_table('accounts')
    op.drop_table('verify_codes')
    op.drop_table('users')
    # ### end Alembic commands ###
