"""v4

Revision ID: ab14e90c669c
Revises: f053344ad331
Create Date: 2025-04-07 13:57:21.834798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab14e90c669c'
down_revision: Union[str, None] = 'f053344ad331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('user_status', sa.String(), nullable=False))
    op.drop_column('users', 'user_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('accounts', 'user_status')
    # ### end Alembic commands ###
